//necromancy spell flags - set to true when the Avatar has learned the spell, default false
enum necromancySpells {
	LEARNED_OPEN_GROUND_SPELL = 0x500,
	LEARNED_CALL_QUAKE_SPELL = 0x501,
	LEARNED_ROCK_FLESH_SPELL = 0x502,
	LEARNED_CREATE_GOLEM_SPELL = 0x503,
	LEARNED_DEATH_SPEAK_SPELL = 0x504,
	LEARNED_MASK_OF_DEATH_SPELL = 0x505,
	LEARNED_SUMMON_DEAD_SPELL = 0x506,
	LEARNED_WITHSTAND_DEATH_SPELL = 0x507,
	LEARNED_GRANT_PEACE_SPELL = 0x508
};