import type { NPCFile, SidecarMeta } from './types';

// The JSON files are served from public/data/ at build time.
// At runtime they're at ./data/ relative to the page.
// The manifest is a JSON array of filenames generated by the build step.
const DATA_BASE = './data';
const META_BASE = './meta';

export type FlagMeta = { bits: number; max: number };

export async function loadManifest(): Promise<string[]> {
  const resp = await fetch(`${DATA_BASE}/manifest.json`);
  if (!resp.ok) throw new Error(`Failed to load manifest: ${resp.status}`);
  return resp.json();
}

export async function loadFlagMetadata(): Promise<Record<string, FlagMeta>> {
  try {
    const resp = await fetch(`${DATA_BASE}/flag_metadata.json`);
    if (!resp.ok) return {};
    return resp.json();
  } catch {
    return {};
  }
}

export async function loadNpcFile(filename: string): Promise<NPCFile> {
  const resp = await fetch(`${DATA_BASE}/${filename}`);
  if (!resp.ok) throw new Error(`Failed to load ${filename}: ${resp.status}`);
  return resp.json();
}

export async function loadAllNpcs(): Promise<NPCFile[]> {
  const filenames = await loadManifest();
  // Load in parallel batches of 50 to avoid flooding the browser.
  const results: NPCFile[] = [];
  const batchSize = 50;
  for (let i = 0; i < filenames.length; i += batchSize) {
    const batch = filenames.slice(i, i + batchSize);
    const loaded = await Promise.all(batch.map(f => loadNpcFile(f)));
    results.push(...loaded);
  }
  return results;
}

export function sidecarFilenameForNpc(npcName: string): string {
  const cls = npcName.startsWith('U8P_') ? npcName : `U8P_${npcName}`;
  return `${cls}_META.JSON`;
}

export async function loadSidecarMetaForNpc(npcName: string): Promise<SidecarMeta | null> {
  const filename = sidecarFilenameForNpc(npcName);
  try {
    const resp = await fetch(`${META_BASE}/${filename}`);
    if (!resp.ok) return null;
    return resp.json();
  } catch {
    return null;
  }
}

export function buildNpcIndex(npcs: NPCFile[]): Record<string, NPCFile> {
  return Object.fromEntries(npcs.map(n => [n.npc, n]));
}

// Collect all unique flags across every NPC, with metadata about which
// NPCs read/write each flag.
export function buildFlagIndex(npcs: NPCFile[]): Map<string, { readers: string[]; writers: string[] }> {
  const index = new Map<string, { readers: string[]; writers: string[] }>();
  
  const ensure = (flag: string) => {
    let entry = index.get(flag);
    if (!entry) { entry = { readers: [], writers: [] }; index.set(flag, entry); }
    return entry;
  };

  for (const npc of npcs) {
    if (npc.flags) {
      for (const f of npc.flags.read) ensure(f).readers.push(npc.npc);
      for (const f of npc.flags.write) ensure(f).writers.push(npc.npc);
    }
  }

  return index;
}
